/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as ViagensIndexRouteImport } from './routes/viagens.index'
import { Route as ViagensTripIdRouteImport } from './routes/viagens.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensIndexRoute = ViagensIndexRouteImport.update({
  id: '/viagens/',
  path: '/viagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensTripIdRoute = ViagensTripIdRouteImport.update({
  id: '/viagens/$tripId',
  path: '/viagens/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despesas': typeof DespesasRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/despesas': typeof DespesasRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/viagens': typeof ViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despesas': typeof DespesasRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/despesas' | '/viagens/$tripId' | '/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/despesas' | '/viagens/$tripId' | '/viagens'
  id: '__root__' | '/' | '/despesas' | '/viagens/$tripId' | '/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespesasRoute: typeof DespesasRoute
  ViagensTripIdRoute: typeof ViagensTripIdRoute
  ViagensIndexRoute: typeof ViagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/': {
      id: '/viagens/'
      path: '/viagens'
      fullPath: '/viagens/'
      preLoaderRoute: typeof ViagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/$tripId': {
      id: '/viagens/$tripId'
      path: '/viagens/$tripId'
      fullPath: '/viagens/$tripId'
      preLoaderRoute: typeof ViagensTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespesasRoute: DespesasRoute,
  ViagensTripIdRoute: ViagensTripIdRoute,
  ViagensIndexRoute: ViagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
