/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as PoupancaRouteImport } from './routes/poupanca'
import { Route as ViagensIndexRouteImport } from './routes/viagens.index'
import { Route as ViagensTripIdRouteImport } from './routes/viagens.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const PoupancaRoute = PoupancaRouteImport.update({
  id: '/poupanca',
  path: '/poupanca',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensIndexRoute = ViagensIndexRouteImport.update({
  id: '/viagens/',
  path: '/viagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensTripIdRoute = ViagensTripIdRouteImport.update({
  id: '/viagens/$tripId',
  path: '/viagens/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/despesas': typeof DespesasRoute
  '/poupanca': typeof PoupancaRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/despesas': typeof DespesasRoute
  '/poupanca': typeof PoupancaRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/viagens': typeof ViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/despesas': typeof DespesasRoute
  '/poupanca': typeof PoupancaRoute
  '/viagens/$tripId': typeof ViagensTripIdRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/despesas'
    | '/poupanca'
    | '/viagens/$tripId'
    | '/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/despesas'
    | '/poupanca'
    | '/viagens/$tripId'
    | '/viagens'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/despesas'
    | '/poupanca'
    | '/viagens/$tripId'
    | '/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  DespesasRoute: typeof DespesasRoute
  PoupancaRoute: typeof PoupancaRoute
  ViagensTripIdRoute: typeof ViagensTripIdRoute
  ViagensIndexRoute: typeof ViagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poupanca': {
      id: '/poupanca'
      path: '/poupanca'
      fullPath: '/poupanca'
      preLoaderRoute: typeof PoupancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/': {
      id: '/viagens/'
      path: '/viagens'
      fullPath: '/viagens/'
      preLoaderRoute: typeof ViagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/$tripId': {
      id: '/viagens/$tripId'
      path: '/viagens/$tripId'
      fullPath: '/viagens/$tripId'
      preLoaderRoute: typeof ViagensTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  DespesasRoute: DespesasRoute,
  PoupancaRoute: PoupancaRoute,
  ViagensTripIdRoute: ViagensTripIdRoute,
  ViagensIndexRoute: ViagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
